version: "3.7"
services:
  pl-admin:
    image: viva/pl-admin
    container_name: pl-admin
    ports:
      - "8000:4000"
    build:
      context: '.'
      args:
        - GIT_NAME=${GIT_NAME}
        - GIT_EMAIL=${GIT_EMAIL}
    volumes:
      - .:/app
      - ${PLSQL_PATH}:/plsql
    tty: true
    networks:
      - backend
    environment:
      - DB_SERVICE_NAME=${DB_SERVICE_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MAIN_SCHEMA=${DB_MAIN_SCHEMA}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_DEFAULT_TABLE_SPACE=${DB_DEFAULT_TABLE_SPACE}
      - DB_TEMP_TABLE_SPACE=${DB_TEMP_TABLE_SPACE}
networks:
  backend:
volumes:
  data:
