version: "3.7"
services:
  plsql-manager:
    image: viva/plsql-manager
    container_name: plsql-manager
    build:
      context: './'
    volumes:
      - ./:/app
      - ${PLSQL_PATH}:/plsql
    tty: true
    networks:
      - backend
    environment:
      - DEBUG=False
      - TESTING=False
      - DB_SERVICE_NAME=DIAOMEGA
      - DB_HOST=maisi.om.do
      - DB_USER=WDELACRUZ4
      - DB_PASSWORD=temp
      - DB_PORT=1521
      - DB_ADMIN_USER=sys
      - DB_ADMIN_PASSWORD=infinityqx35
      - DB_DEFAULT_TABLE_SPACE=OMEGA_DATA
      - DB_TEMP_TABLE_SPACE=TEMP_TBS
      - DB_MAIN_SCHEMA=OMEGA
networks:
  backend:
volumes:
  data:
